		<div id="menu_as">
			<ul>
				<li><a href="index.html" title="Get updated on the latest Alien Swarm news">News</a></li>
				<li><a href="info.html" title="Read about the game">Info</a></li>
				<li><a href="screenshots.html" title="See screenshots">Screenshots</a></li>
				<li><a href="concept.html" title="See concept art">Concept Art</a></li>
				<li><a href="download.html" title="Download the latest version">Download</a></li>
				<li><a href="mappingdocs.html" title="Learn how to map">Mapping Docs</a></li>
				<li><a href="serverdocs.html" title="Learn how to run dedicated servers">Server Docs</a></li>
				<li><a href="fanmaps.html" title="Check out these featured Alien Swarm fan-made maps and campaigns.">Fan-made Maps</a></li>
				<li><a href="awards.html" title="Check what awards Alien Swarm has been given">Awards</a></li>
				<li><a href="team.html" title="See who's on the team, and contact us">Team</a></li>
				<li><a href="links.html" title="Links to other websites">Links</a></li>
				<li><a href="http://forums.blackcatgames.com/" title="Visit the community forums">Forums</a></li>
			</ul>
		</div>
		
		<div id="menu_asv2">
			<p><a href="index.html" title="Alien Swarm: Infested">Play the new Alien Swarm game, built on the Source Engine!</a></p>
		</div>

		<div id="swarm_random">
			<script type="text/javascript" src="swarm_news.js"></script>

			<div id="copyright_notice">
				<p><a href="http://www.blackcatgames.com" title="Visit our homepage">Black Cat Games</a></p>
			</div>
		</div>