var newsitems = new Array();
	newsitems[0] = "<p><b>Alpha Prison Riots</b></p><p>ISAF reports riots on the prison colony of Alpha 7826-X in the Luyten system. A squad of marines were dispatched this morning to resecure the colony, under orders to terminate any uncooperative in-mates. The planet's automated orbital security systems have already taken out two shuttles attempting to leave the surface of the planet without proper authorisation codes. It is assumed that all current prison guards on the colony have been killed in the riots.</p>";
	newsitems[1] = "<p><b>Swarm activities on the increase, human casualties at an all time high.</b></p><p>More outlying human colonies have fallen to Swarm attacks this month, the most notable of which being the research base of Tau Ceti 5. This base was known for its intensive research on the alien threat, having produced a number of papers on their behaviour and biological makeup, information the ISAF paid a great deal for. It's unknown whether the attack on this base was caused by the recent presence of a number of recently captured live bugs or whether it was just a random attack.</p>";
	newsitems[2] = "<p><b>SynTek calls for reevaluation of mechanoid assault droid laws.</b></p><p>After losing control of yet another mining/refinery plant on the outlying worlds, the SynTek Megacorporation is calling for the Interstellar Alliance to reevaluate its laws on military androids. Law currently prohibits any non-ISAF party from manufacturing or deploying mechanoids capable of harming biological lifeforms and even the ISAF has only used its military droids on remote worlds with minimum civilian exposure.</p><p>These tight laws have been in place since the Rosebloom Pleasure World Massacre of '84, in which a single malfunctioning droid destroyed the Starport and communications array, then systematically killed over a million tourists before it was disabled by a group of ISAF marines on shore leave.</p>";
	newsitems[3] = "<p><b>Join the ISAF!</b></p><p>With the Swarm threat on the increase, the Interstellar Armed Forces are receiving additional recruitment funding, with new training camps being set up across the Allied Systems. If you're between the ages of 18 and 35 and looking for a strong military career with good promotion prospects, excellent pay and the ability to do your part for the human race, contact your local recruitment office immediately.</p>";
	newsitems[4] = "<p><b>Swarm attack claims 'Indestructable' Passenger Ship</b></p><p>After an impressive launch last October, the interstellar long-distance passenger ship 'Titanic' fell victim to a vicious Swarm attack. Despite Spacefarer Inc.'s best attempts to build an impenetrable sleeper ship, the bugs still managed to puncture the hull and kill all 15,000 civilians resting in hypersleep and the skeleton crew. The ship was found drifting off course near the Alpha Minor star system, where ISAF forces have commandeered the vessel until further notice.</p>";
	newsitems[5] = "<p><b>More efficient EMP stims?</b></p><p>A recent survey team running tests on an undisclosed outer system world have reported finding a strange mineral on the desert planet which increases a person's empathic ablities. The pharmaceutical branch of SynTek believes this dust could be used to produce more powerful EMP stim packs.</p>";
	
	storynum = Math.round(Math.random()*5);
	
	document.writeln(newsitems[storynum]);